# لتعلم المزيد عن Buck، راجع [التوثيق](https://buckbuild.com/).
# لتشغيل تطبيقك باستخدام Buck:
# - قم بتثبيت Buck
# - `npm start` - لبدء الحزمة
# - `cd android` - انتقل إلى مجلد android
# - `keytool -genkey -v -keystore keystores/debug.keystore -storepass android -alias androiddebugkey -keypass android -dname "CN=Android Debug,O=Android,C=US"` - إنشاء مفتاح توقيع للتطبيق
# - `./gradlew :app:copyDownloadableDepsToLibs` - جعل جميع تبعيات Gradle متاحة لـ Buck
# - `buck install -r android/app` - ترجمة، تثبيت، وتشغيل التطبيق
#

load(":build_defs.bzl", "create_aar_targets", "create_jar_targets")

lib_deps = []

create_aar_targets(glob(["libs/*.aar"]))

create_jar_targets(glob(["libs/*.jar"]))

android_library(
    name = "all-libs",
    exported_deps = lib_deps,
)

android_library(
    name = "app-code",
    srcs = glob([
        "src/main/java/**/*.java",
    ]),
    deps = [
        ":all-libs",
        ":build_config",
        ":res",
    ],
)

android_build_config(
    name = "build_config",
    package = "com.akojdad.novels",
)

android_resource(
    name = "res",
    package = "com.akojdad.novels",
    res = "src/main/res",
)

android_binary(
    name = "app",
    keystore = "//android/keystores:debug",
    manifest = "src/main/AndroidManifest.xml",
    package_type = "debug",
    deps = [
        ":app-code",
    ],
)